/**
 * The brand mascot, from public/mascot.svg (generated by
 * scripts/src/generate-brand.ts). Decorative - the text beside it carries the
 * meaning - so it has empty alt text and is hidden from screen readers.
 */
export function Mascot({ size = 72, className = '' }: { size?: number; className?: string }) {
  return (
    // A static SVG from public/: next/image would only add a request.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/mascot.svg"
      alt=""
      aria-hidden
      width={size}
      height={size}
      className={`select-none ${className}`}
    />
  )
}
