/**
 * The brand mascot: a map pin with a Sagittarius personality, from
 * public/logo.svg (generated by scripts/src/generate-brand.ts).
 *
 * Decorative wherever it appears - the text beside it always carries the
 * meaning - so it has empty alt text and is hidden from screen readers.
 */
export function Logo({
  size = 96,
  bob = false,
  className = '',
}: {
  size?: number
  /** A slow float, for the one place the mascot is the centre of attention. */
  bob?: boolean
  className?: string
}) {
  return (
    // A static SVG from public/: next/image would only add a request.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src="/logo.svg"
      alt=""
      aria-hidden
      width={size}
      height={size}
      className={`select-none ${bob ? 'animate-bob' : ''} ${className}`}
    />
  )
}
